#Version of docker compose syntax. Ensures we're targeting 
#the current versiona t the time this was built
version: "3.9"

#This defines the service for our app
services: 
  app:
    #Build the docker file in our current directory
    build:
      context: .
      #If we run using docker-compose, we set a build time argument "DEV" set to true
      args:
        - DEV=true
    #Maps port 8000 on our local machine to port 8000 in the docker container
    ports:
      - "8000:8000"
    #maps the directory in our system to the directory in the coker container
    #<local_dir>:<container_dir>
    volumes:
      - ./app:/app
    #Command that will run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"