#Version of docker compose syntax. Ensures we're targeting 
#the current version at the time this was built
version: "3.9"

#This defines our services
services: 
  #defines a service named "app"
  app:
    #Build the docker file in our current directory
    build:
      context: .
      #If we run using docker-compose, we set a build time argument "DEV" set to true
      args:
        - DEV=true
    #Maps port 8000 on our local machine to port 8000 in the docker container
    ports:
      - "8000:8000"
    #maps the directory in our system to the directory in the coker container
    #<local_dir>:<container_dir>
    volumes:
      - ./app:/app
    #Command that will run the service
    # running wait_for_db to ensure the db is ready, migrating it, and then starting server.
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      #db is the name of the service created by docker compose named below.
      #It is configured to use the same dev db name, and credentials  also specified in the below service.
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    #defines the DB service as a dependancy.
    #This ensures we start the DB, but not that it's running and available
    # will need to fix this race condition.
    depends_on:
      - db


  #defines a service named "db"
  db:
    #https://hub.docker.com/_/postgres
    #Alpine is a lighter weight version of postgres
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
      #sets the initial config for the DB, named "devdb" and adds a user "devuser" with a password "changeme"
      #all of these credentials are just for local dev testing purposes, and wont be useful for any production
      #related database values
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  #name of the volume
  #No need to add anything else, docker compose will store this in the default location
  dev-db-data: